"""empty message

Revision ID: 9da137bca961
Revises: dbc234a19188
Create Date: 2021-05-12 10:31:13.116250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da137bca961'
down_revision = 'dbc234a19188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('roles', sa.Text(), nullable=False))
    op.drop_column('review', 'theater')
    op.add_column('view', sa.Column('comment', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view', 'comment')
    op.add_column('review', sa.Column('theater', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('review', 'roles')
    # ### end Alembic commands ###
